#!/usr/bin/env python3
"""ADO <-> Northwind reconciliation PARITY test.

The unit test (test_normalize_ado.py) proves the parser. It does NOT prove that the ADO
lane reconciles like the existing lanes, because its fixtures are unrelated to the
Northwind corpus (so reconcile.py ado correctly returns zeros — a non-test).

This test closes that gap: it mirrors the Northwind BACKLOG as an ADO CSV
(tests/fixtures/ado/ado_northwind_backlog.csv, generated by gen_northwind_ado.py),
runs it through the SAME drafted Keel state as the backlog lane, and asserts:

  1. Canonical parity  — normalize_ado maps the mirrored content to the SAME canonical
     (type, status) as normalize_backlog, for every item (incl. `blocked` via a custom
     state map — proving stock ADO's gap on blocked/analysis is covered by the override).
  2. Reconcile parity  — 23 of 25 portfolio items land in the SAME reconcile bucket
     through both lanes. The ONLY two divergences are the ref-embedded plants
     (title-drift NWR-122, embedded-key NWR-142): the backlog resolves them via the NWR
     key in its Notes field; an ADO CSV export has no such field, so they fall back to
     title matching (changed -> ambiguous / gap). That is a property of the source
     format, not a defect — and this test pins it so it can't regress silently.

STATEFUL, on-demand (like run_e2e.sh): it regenerates the demo corpus and drafts demo
state into state/. Do NOT run on a deployment holding real data. Separate from the pure
unit test. Run:  python3 tests/test_ado_parity.py   (needs openpyxl + PyYAML; no LLM.)
"""
import json, os, subprocess, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MIRROR = ROOT / "tests" / "fixtures" / "ado" / "ado_northwind_backlog.csv"
RECON = ROOT / "state" / "normalized" / "reconcile.json"
# Custom process state map — covers blocked/analysis that stock ADO templates don't.
ADO_STATE_MAP = '{"new":"not-started","active":"in-progress","closed":"done","blocked":"blocked","analysis":"analysis"}'

# The two backlog plants that rely on the NWR key in Notes; ADO CSV can't carry it.
REF_ONLY_DIVERGENCES = {
    "End-of-shift handover report": ("changed", "ambiguous"),   # title-drift NWR-122
    "Validate site configs before rollout": ("changed", "gap"), # embedded-key NWR-142
}
EXPECTED_ADO_BUCKETS = {"changed": 19, "gap": 4, "ambiguous": 2}

FAILS = []
def check(name, got, want):
    ok = got == want
    print(f"  {'PASS' if ok else 'FAIL'}  {name}: {got!r}" + ("" if ok else f"  (want {want!r})"))
    if not ok:
        FAILS.append(name)

def run(*args, env=None):
    e = dict(os.environ); e.update(env or {})
    p = subprocess.run([sys.executable, *args], cwd=ROOT, env=e, capture_output=True, text=True)
    if p.returncode != 0:
        print(f"  SETUP FAILED: {' '.join(args)}\n{p.stdout}\n{p.stderr}")
        sys.exit(2)

def buckets_now():
    b = json.loads(RECON.read_text(encoding="utf-8"))["buckets"]
    return {k: [i.get("src_name") for i in v] for k, v in b.items() if isinstance(v, list)}

def main():
    if not MIRROR.exists():
        print(f"  missing mirror {MIRROR}; regenerate: python3 tests/fixtures/ado/gen_northwind_ado.py")
        sys.exit(2)

    # --- setup: corpus + drafted state + backlog baseline (deterministic, no LLM) ---
    run("examples/northwind/gen_corpus.py", ".")
    run("tools/normalize_jira.py")
    run("tools/reconcile.py", "jira")
    run("tools/apply.py", "--commit")
    run("tools/normalize_backlog.py")
    run("tools/reconcile.py", "backlog")
    backlog_bkt = buckets_now()
    backlog_bucket_of = {n: bk for bk, names in backlog_bkt.items() for n in names}

    # --- ADO lane over the mirror (custom state map) ---
    run("tools/normalize_ado.py", str(MIRROR), "--template", "northwind", env={"ADO_STATE_MAP": ADO_STATE_MAP})
    ado_norm = json.loads((ROOT / "state" / "normalized" / "ado.json").read_text(encoding="utf-8"))
    run("tools/reconcile.py", "ado")
    ado_bkt = buckets_now()
    ado_bucket_of = {n: bk for bk, names in ado_bkt.items() for n in names}

    # 0) baseline sanity: backlog reproduces the oracle's frozen landings
    exp = json.loads((ROOT / "expectations.json").read_text(encoding="utf-8"))["backlog_reconcile"]["buckets"]
    check("backlog baseline == oracle", {k: len(v) for k, v in backlog_bkt.items() if v},
          {k: v for k, v in exp.items() if v})

    # 1) canonical parity: ADO maps identical content to identical (type, status)
    bl = {r["name"]: (r["type"], r["status"]) for r in json.loads((ROOT / "state" / "normalized" / "backlog.json").read_text(encoding="utf-8"))["rows"]}
    ad = {r["name"]: (r["type"], r["status"]) for r in ado_norm["rows"]}
    mismatches = sorted(n for n in ad if n in bl and ad[n] != bl[n])
    check("canonical parity: ADO type+status == backlog (by title)", mismatches, [])
    check("canonical parity: row count", len(ad), 26)
    check("custom map covered blocked (no unmapped)", ado_norm["status_counts"].get("blocked"), 1)
    check("no unmapped statuses in mirror", [s for s in ado_norm["status_counts"] if s.startswith("unmapped:")], [])

    # 2) reconcile bucket parity
    check("ADO bucket counts", {k: len(v) for k, v in ado_bkt.items() if v}, EXPECTED_ADO_BUCKETS)
    portfolio_items = sorted(set(backlog_bucket_of) | set(ado_bucket_of))
    same = [n for n in portfolio_items if backlog_bucket_of.get(n) == ado_bucket_of.get(n)]
    check("items landing in the SAME bucket through both lanes", len(same), 23)

    diverged = {n: (backlog_bucket_of.get(n), ado_bucket_of.get(n))
                for n in portfolio_items if backlog_bucket_of.get(n) != ado_bucket_of.get(n)}
    check("the ONLY divergences are the two ref-embedded plants", diverged, REF_ONLY_DIVERGENCES)

    # 3) named-plant parity (the pieces that must behave the same)
    check("3 backlog gaps are a subset of ADO gaps", set(backlog_bkt.get("gap", [])) <= set(ado_bkt.get("gap", [])), True)
    check("ambiguous-paraphrase is ambiguous in BOTH lanes",
          (backlog_bucket_of.get("Autonomous vehicle fleet navigation"),
           ado_bucket_of.get("Autonomous vehicle fleet navigation")), ("ambiguous", "ambiguous"))
    check("status-drift item is 'changed' in BOTH lanes",
          (backlog_bucket_of.get("Operator can pause a single robot"),
           ado_bucket_of.get("Operator can pause a single robot")), ("changed", "changed"))

    print()
    if FAILS:
        print(f"PARITY: FAIL ({len(FAILS)}): {', '.join(FAILS)}")
        sys.exit(2)
    print("PARITY: ALL PASS  (23/25 same bucket; 2 documented ref-format divergences)")

if __name__ == "__main__":
    main()
